ERRORS = {
    "err1": "Application failed to load",
    "err2": "Application crashed",
    "err3": "Invalid request parameters",
    "err4": "Resource not found",
    "err5": "Unauthorized access",
    "err6": "Authentication failed",
    "err7": "Access forbidden",
    "err8": "Internal server error",
    "err9": "Service unavailable",
    "err10": "Database connection error",
    "err11": "Invalid data format",
    "err12": "Request timeout",
    "err13": "Exceeded request limit",
    "err14": "Conflict detected in request",
    "err15": "Duplicate entry",
    "err16": "Required field missing",
    "err17": "Invalid email or password",
    "err18": "Session expired",
    "err19": "File upload error",
    "err20": "Unsupported media type",
    "err21": "Operation not allowed",
    "err22": "Dependency service failure",
    "err23": "Data validation error",
    "err24": "Account locked",
    "err25": "Invalid token",
    "err26": "Token expired",
    "err27": "Invalid API key",
    "err28": "Malformed request",
    "err29": "Operation timeout",
    "err30": "Resource already exists",
}
